### ISSUE TITLE
Temporary files should be in a temporary directory

### ISSUE THREAD

**Issue by glynnbird** [Choirless/Stitcheroo#3]
If I include Stitcheroo as a module and ask it to stitch some videos together with `false` as the second parameter, it returns me the path to generated video:

```js
  const filename = await sticheroo(videos, false)
  console.log(filename)
```

Unfortunately, the generated file is stored inside my `node_modules` directory along with the Stitcheroo code e.g.

```
/Users/glynnbird/projects/renderer/node_modules/stitcheroo/hrXxl3Tqq.mp4
```

A better place to store the output file would be:

```
/<some temporary directory>/hrXxl3Tqq.mp4
```

as the node_modules directory may be readonly a real temporary directory is always world writable and files are ephemeral.

See [os.tmpdir()](https://nodejs.org/dist/latest-v12.x/docs/api/os.html#os_os_tmpdir)

**Comment by seanmtracey** [comment]
Resolved by #10
